<Project>
    <ItemGroup>
        <CopyDestination Include="$(MSBuildProjectDirectory)/../Release/$(ModName)/" />
    </ItemGroup>

    <Target Name="CopyBuildOutput" AfterTargets="Build">
        <MSBuild Projects="$(MSBuildProjectFile)" Targets="_CopyToSingleDestination" Properties="SingleCopyDestination=%(CopyDestination.Identity)" />
    </Target>

    <Target Name="_CopyToSingleDestination">
        <Message Text="Refreshing $(SingleCopyDestination)" Importance="high" />

        <!-- Collect files here -->
        <ItemGroup>
            <FilesToCopy Include="$(OutputPath)**\*" />
        </ItemGroup>

        <!-- Remove existing directory -->
        <RemoveDir Directories="$(SingleCopyDestination)" />

        <!-- Recreate -->
        <MakeDir Directories="$(SingleCopyDestination)" />

        <!-- Copy preserving structure -->
        <Copy SourceFiles="@(FilesToCopy)" DestinationFiles="@(FilesToCopy->'$(SingleCopyDestination)%(RecursiveDir)%(Filename)%(Extension)')" />

        <ItemGroup>
            <ModManifestLines Include="name = &quot;$(ModName)&quot;" />
            <ModManifestLines Include="version = &quot;v$(Version)&quot;" />
            <ModManifestLines Include="author = &quot;$(Authors)&quot;" />
            <ModManifestLines Include="description = &quot;$(Description)&quot;" />
            <ModManifestLines Include="[StarMap]">
                <Separator>$([System.Environment]::NewLine)</Separator>
            </ModManifestLines>
            <ModManifestLines Include="EntryAssembly = &quot;$(AssemblyName)&quot;" />
        </ItemGroup>

        <WriteLinesToFile File="$(SingleCopyDestination)mod.toml" Lines="@(ModManifestLines->'%(Separator)%(Identity)')" Overwrite="true" />
    </Target>
</Project>