<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <ModFile Include="$(OutputPath)\$(ModName).dll" />
    <ModFile Include="..\Content\**\*" />

    <_KsaAssemblies Include="$(KSADir)Brutal*.dll" Path="%(FullPath)" />
    <_KsaAssemblies Include="$(KSADir)KSA.dll" Path="%(FullPath)" />
    <_KsaAssemblies Include="$(KSADir)Planet*.dll" Path="%(FullPath)" />
    <_KsaAssemblies Include="$(KSADir)Tomlet.dll" Path="%(FullPath)" />
    <Reference Include="@(_KsaAssemblies->'%(FileName)')" HintPath="%(Path)" Private="False" />

  </ItemGroup>
</Project>