<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="ShaderExtensions.props" />
	<PropertyGroup>
		<Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
		<Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
		<TargetFramework>net10.0</TargetFramework>
		<TargetFrameworkVersion>net10.0</TargetFrameworkVersion>
		<LanguageTargets>$(MSBuildToolsPath)\Microsoft.CSharp.targets</LanguageTargets>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<LangVersion>latest</LangVersion>
		<OutputPath>bin\$(Configuration)</OutputPath>
		<AssemblyName>$(ModName)</AssemblyName>
		<OutputType>Library</OutputType>

		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Configurations>Debug;Release</Configurations>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>

		<VersionPrefix>1.0.1</VersionPrefix>
		<Version>$(VersionPrefix)</Version>
		<AssemblyVersion>1.0.0.0</AssemblyVersion>
		<FileVersion>$(VersionPrefix).0</FileVersion>

		<GitShortHash>nogit</GitShortHash>
		<InformationalVersionPostfix></InformationalVersionPostfix>
		<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>

		<Company>AMPW</Company>
		<Authors>AMPW</Authors>
		<Copyright>MIT</Copyright>
	</PropertyGroup>

	<PropertyGroup>
		<DebugSymbols>true</DebugSymbols>
		<DebugType>portable</DebugType>
		<ErrorReport>prompt</ErrorReport>
		<WarningLevel>4</WarningLevel>
		<Prefer32Bit>false</Prefer32Bit>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
		<InformationalVersionPostfix>-debug</InformationalVersionPostfix>
		<DefineConstants>DEBUG;TRACE</DefineConstants>
		<Optimize>false</Optimize>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
		<Optimize>true</Optimize>
		<DefineConstants>TRACE</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Lib.Harmony" Version="2.4.2" />
		<PackageReference Include="ModMenu.Attributes" Version="1.0.1" />
		<PackageReference Include="StarMap.API" Version="0.3.6" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="KittenExtensions">
			<HintPath>..\..\..\..\Documents\My Games\Kitten Space Agency\mods\KittenExtensions\KittenExtensions.dll</HintPath>
			<Private>False</Private>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<None Update="mod.toml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<Target Name="SetVersionMetadata" BeforeTargets="GetAssemblyVersion">
		<Exec Command="git rev-parse --short HEAD" ConsoleToMSBuild="true" IgnoreExitCode="true" IgnoreStandardErrorWarningFormat="true">
			<Output TaskParameter="ConsoleOutput" PropertyName="GitShortHashRaw" />
		</Exec>

		<PropertyGroup>
			<GitShortHash Condition="'$(GitShortHashRaw)' != ''">$([System.String]::Copy('$(GitShortHashRaw)').Trim())</GitShortHash>
			<GitShortHash Condition="'$(GitShortHash)' == ''">nogit</GitShortHash>
			<InformationalVersion>v$(VersionPrefix).$(GitShortHash)$(InformationalVersionPostfix)</InformationalVersion>
			<ProductVersion>$(InformationalVersion)</ProductVersion>
		</PropertyGroup>
	</Target>

	<Import Project="CopyOutput.targets" />
</Project>
